### ISSUE TITLE
Create a form listener that can be wired in to simply persist the object to database

### ISSUE THREAD

**Issue by silverbackdan** [silverbackis/api-components-bundle#20]
Often it will be needed that when a form is submitted, we simply need to persist that object to the database. We are doing this already for the user registrations and new email address form types.

I have seen this done before on other packages but cannot remember where.

So the config would be something like:
```yaml
services:
    'app.listener.contact_form':
        class: Silverback\ApiComponentBundle\EventListener\Form\EntityPersister
        arguments:
            $formType: App\Form\ContactType
            $dataClass: App\Entity\ContactSubmission
```
